"use client";
import Image from "next/image";
import { useMemo,useState } from "react";
import { createClient } from "genlayer-js";
import { studionet } from "genlayer-js/chains";
import { TransactionStatus } from "genlayer-js/types";
import { BookOpenCheck,ExternalLink,FileClock,Landmark,Link2,LoaderCircle,SearchCheck,ShieldCheck,WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";
declare global { interface Window { ethereum?: unknown } }
type Watch={watch_id:string;owner:string;ocid:string;status:string;criteria_release_id:string;criteria_sha256:string;criteria:Array<{criterion_id:string;text:string;weight_band:string}>;award_release_id:string;award_sha256:string;revision_count:number;current_revision:string};
const OCID="ocds-b5fd17-9b2e0c20-6781-471b-8b29-c2d639187ed0", RELEASE="a55ff105-de10-4260-b843-e16e40642436", DIGEST="88049adca6e69542352867906d1b234cf3f698e36121db02e20892cecf2f278a", CONTRACT="0x3587E5d4cc060718a4b7E4b2aA77A6AcC7f44aC1", EXPLORER="https://explorer-studio.genlayer.com";

export default function Home(){
 const [account,setAccount]=useState(""),[contract,setContract]=useState(CONTRACT),[watchId,setWatchId]=useState("3"),[busy,setBusy]=useState("");
 const [watch,setWatch]=useState<Watch|null>(null),[revision,setRevision]=useState<Record<string,unknown>|null>(null),[journal,setJournal]=useState<Array<{label:string;hash:string}>>([]);
 const valid=/^0x[0-9a-fA-F]{40}$/.test(contract), readClient=useMemo(()=>createClient({chain:studionet}),[]);
 async function connect(){if(!window.ethereum)return toast.error("No injected wallet found.");try{const accounts=await(window.ethereum as {request:(x:{method:string})=>Promise<string[]>}).request({method:"eth_requestAccounts"});const selected=accounts[0];const client=createClient({chain:studionet,account:selected as `0x${string}`,provider:window.ethereum});await client.connect("studionet");setAccount(selected);toast.success("Wallet connected to StudioNet")}catch(e){toast.error(e instanceof Error?e.message:"Wallet connection cancelled")}}
 function saveContract(v:string){v=v.trim();setContract(v);localStorage.setItem("awardtrace.contract",v);setWatch(null);setRevision(null)}
 async function readBack(id:string){const raw=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_watch",args:[id]});if(raw==="NOT_FOUND")throw new Error("Watch not found");const parsed=JSON.parse(String(raw)) as Watch;setWatch(parsed);if(parsed.current_revision!==""){const rev=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_revision",args:[id,parsed.current_revision]});setRevision(JSON.parse(String(rev)))}else setRevision(null)}
 async function refresh(id=watchId){if(!valid)return toast.error("Set the deployed contract address first.");setBusy("read");try{await readBack(id);toast.success("Authoritative contract state loaded.")}catch(e){toast.error(e instanceof Error?e.message:"Read failed")}finally{setBusy("")}}
 async function write(label:string,method:string,args:string[]){if(!valid)return toast.error("Set the deployed contract address first.");if(!account||!window.ethereum)return toast.error("Connect a funded StudioNet wallet first.");setBusy(method);try{let targetId=watchId;let countBefore=-1;if(method==="create_watch"){countBefore=Number(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}));targetId=String(countBefore)}const client=createClient({chain:studionet,account:account as `0x${string}`,provider:window.ethereum});await client.connect("studionet");const hash=String(await client.writeContract({address:contract as `0x${string}`,functionName:method,args,value:0n})) as `0x${string}`;setJournal(x=>[{label,hash},...x]);toast.info("Signed. Waiting for finality…");await readClient.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});if(method==="create_watch"){const countAfter=Number(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}));if(countAfter!==countBefore+1)throw new Error("Finalized, but watch count did not advance exactly once");setWatchId(targetId)}await readBack(targetId);toast.success(`${label}: finalized and authoritative state confirmed.`)}catch(e){toast.error(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
 const disabled=!valid||!account||Boolean(busy);
 return <main className="min-h-screen bg-[#f5f8fc] text-[#071b3d]"><Toaster position="top-right" richColors/>
  <header className="sticky top-0 z-40 border-b border-[#c9d8ec] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-3 lg:px-9"><div className="flex items-center gap-3"><Image src="/awardtrace-logo.png" alt="AwardTrace" width={48} height={48} className="rounded-xl" priority/><div><p className="text-lg font-black">AwardTrace</p><p className="text-xs text-[#557092]">Public procurement decision trace</p></div></div><div className="hidden rounded-full border border-[#c7d8ed] bg-[#f8fbff] px-4 py-2 font-mono text-xs md:block">StudioNet · {valid?`${contract.slice(0,8)}…${contract.slice(-6)}`:"deployment pending"}</div><button onClick={connect} className="action primary"><WalletCards size={18}/>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></div></header>
  <section className="mx-auto max-w-[1500px] px-5 py-8 lg:px-9"><div className="mb-7 grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
   <div className="blueprint relative overflow-hidden rounded-[30px] p-7 text-white lg:p-10"><div className="relative z-10 max-w-2xl"><div className="eyebrow text-[#9ed2ff]">OFFICIAL SOURCE → BOUNDED CONSENSUS → PUBLIC TRACE</div><h1 className="mt-4 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">Trace the reason,<br/><span className="text-[#62b2ff]">criterion by criterion.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-[#d8e9ff]">Anchor published tender criteria before an award, then map official award reasoning without treating bidder-authored evidence as ground truth.</p></div><Landmark className="absolute -bottom-12 right-3 h-64 w-64 text-white/5" strokeWidth={1}/></div>
   <div className="panel p-6 lg:p-8"><div className="flex items-center justify-between"><div><div className="eyebrow">ACTIVE SOURCE ADAPTER</div><h2 className="mt-2 text-xl font-black">UK Contracts Finder</h2></div><ShieldCheck className="text-[#087ac1]"/></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt>Authority</dt><dd>Cabinet Office OCDS</dd></div><div><dt>Transport</dt><dd>Single release JSON</dd></div><div><dt>Bound identity</dt><dd>OCID + release GUID</dd></div><div><dt>Integrity</dt><dd>Raw SHA-256 + bytes</dd></div></dl><a className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#075ea7]" href={`https://www.contractsfinder.service.gov.uk/Published/Notice/releases/${RELEASE}.json`} target="_blank">Inspect official resource <ExternalLink size={15}/></a></div>
  </div>
  <div className="mb-6 panel grid gap-4 p-5 md:grid-cols-[1fr_auto]"><label className="field"><span>Deployed contract address</span><input value={contract} onChange={e=>saveContract(e.target.value)} placeholder="Deploy with the primary wallet, then paste 0x…"/></label><div className="flex items-end"><button className="action secondary w-full md:w-auto" onClick={()=>refresh()} disabled={!valid||Boolean(busy)}>{busy==="read"?<LoaderCircle className="animate-spin"/>:<SearchCheck/>}Read contract</button></div></div>
  <Tabs defaultValue="operate" className="gap-5"><TabsList aria-label="AwardTrace sections" className="h-auto w-full justify-start gap-2 overflow-x-auto rounded-2xl border border-[#a9c4e2] bg-[#eaf3ff] p-2 shadow-[0_8px_24px_rgba(7,94,167,.12)]"><TabsTrigger value="operate" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">Operate</TabsTrigger><TabsTrigger value="trace" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">Trace matrix</TabsTrigger><TabsTrigger value="history" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">History</TabsTrigger><TabsTrigger value="evidence" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">Evidence</TabsTrigger></TabsList>
   <TabsContent value="operate"><div className="grid gap-5 lg:grid-cols-[.92fr_1.08fr]"><section className="panel p-6"><Head icon={<BookOpenCheck/>} over="01 · PROSPECTIVE ANCHOR" title="Create procurement watch"/><div className="mt-6 space-y-4"><Input id="ocid" label="Official OCID" value={OCID}/><Input id="release" label="Criteria release GUID" value={RELEASE}/><Input id="digest" label="Raw release SHA-256" value={DIGEST}/></div><button disabled={disabled} className="action primary mt-5" onClick={()=>write("Create watch","create_watch",[val("ocid"),val("release"),val("digest")])}>Create watch</button></section>
   <section className="panel p-6"><Head icon={<FileClock/>} over="02 · LEDGER ACTIONS" title="Advance official trace"/><label className="field mt-6 max-w-40"><span>Watch ID</span><input value={watchId} onChange={e=>setWatchId(e.target.value)}/></label><div className="mt-5 grid gap-3 sm:grid-cols-2"><button disabled={disabled} className="action secondary" onClick={()=>write("Anchor criteria","anchor_criteria",[watchId])}>Anchor criteria</button><button disabled={disabled} className="action secondary" onClick={()=>write("Bind award","bind_award",[watchId,RELEASE,DIGEST])}>Bind award</button><button disabled={disabled} className="action primary" onClick={()=>write("Assess award","assess_award",[watchId])}>Assess award</button><button disabled={disabled} className="action secondary" onClick={()=>write("Freeze trace","freeze_trace",[watchId])}>Freeze trace</button></div><div className="mt-6 rounded-2xl bg-[#eef5ff] p-4 text-sm leading-6 text-[#38577e]">Every write waits for finality, then reads authoritative state back. Wallet signature alone is never shown as business success.</div></section></div></TabsContent>
   <TabsContent value="trace"><section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#d4e0ef] p-6"><div><div className="eyebrow">CURRENT CANONICAL REVISION</div><h2 className="mt-1 text-2xl font-black">{String(revision?.summary||"No assessed trace")}</h2></div><span className="status">{watch?.status||"NOT LOADED"}</span></div><div className="overflow-x-auto"><table><thead><tr><th>Criterion</th><th>Published criterion</th><th>Weight</th><th>Relation</th><th>Official reference</th></tr></thead><tbody>{watch?.criteria.length?watch.criteria.map((c,i)=>{const row=(revision?.trace as Array<Record<string,unknown>>|undefined)?.[i];return <tr key={c.criterion_id}><td className="font-mono font-bold">{c.criterion_id}</td><td>{c.text}</td><td>{c.weight_band}</td><td><span className="relation">{String(row?.relation||"PENDING")}</span></td><td className="font-mono text-xs">{String(row?.award_reference||"—")}</td></tr>}):<tr><td colSpan={5} className="py-14 text-center text-[#69809e]">Load a watch to inspect its criterion-level trace.</td></tr>}</tbody></table></div></section></TabsContent>
   <TabsContent value="history"><div className="grid gap-5 lg:grid-cols-[1fr_.72fr]"><section className="panel p-6"><Head icon={<Link2/>} over="APPEND-ONLY LINEAGE" title="Revision chain"/><div className="mt-7 timeline"><div><b>Criteria anchor</b><span>{watch?.criteria_release_id||"Awaiting watch"}</span></div><div><b>Award observation</b><span>{watch?.award_release_id||"Not bound"}</span></div><div><b>Canonical revision</b><span>{!watch||watch.current_revision===""?"Not assessed":`Revision ${watch.current_revision}`}</span></div></div></section><section className="panel p-6"><div className="eyebrow">TRANSACTION JOURNAL</div><div className="mt-4 space-y-3">{journal.length?journal.map(x=><a key={x.hash} className="journal" href={`${EXPLORER}/tx/${x.hash}`} target="_blank"><span>{x.label}</span><code>{x.hash.slice(0,10)}…{x.hash.slice(-8)}</code></a>):<p className="text-sm text-[#69809e]">Signed writes will appear here with Explorer links.</p>}</div></section></div></TabsContent>
   <TabsContent value="evidence"><section className="panel p-6 lg:p-8"><div className="eyebrow">TEST RESOURCE MANIFEST</div><h2 className="mt-2 text-2xl font-black">Authority before interpretation</h2><div className="mt-7 grid gap-4 md:grid-cols-3"><Evidence title="Official release" detail="Cabinet Office OCDS · award tag" value="8,491 raw bytes"/><Evidence title="Immutable observation" detail="Exact GUID + digest" value={`${DIGEST.slice(0,14)}…`}/><Evidence title="Synthetic fixtures" detail="Parser/adversarial tests only" value="Never live ground truth"/></div><p className="mt-6 max-w-3xl text-sm leading-7 text-[#4c6688]">AwardTrace does not claim procurement legality, fairness, value for money, or absence of corruption. The bundled award-tagged sample demonstrates source binding and trace mechanics, not a real pre-award anchor. Prospective evidence requires an earlier tender release and a later award release for the same OCID.</p></section></TabsContent>
  </Tabs></section></main>
}
const val=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;
function Head({icon,over,title}:{icon:React.ReactNode;over:string;title:string}){return <div className="section-head"><span>{icon}</span><div><div className="eyebrow">{over}</div><h2>{title}</h2></div></div>}
function Input({id,label,value}:{id:string;label:string;value:string}){return <label className="field"><span>{label}</span><input id={id} defaultValue={value}/></label>}
function Evidence({title,detail,value}:{title:string;detail:string;value:string}){return <div className="rounded-2xl border border-[#cbd9eb] bg-[#f8fbff] p-5"><p className="font-black">{title}</p><p className="mt-1 text-sm text-[#68809e]">{detail}</p><code className="mt-5 block text-xs text-[#075ea7]">{value}</code></div>}
