"use client";
import Image from "next/image";
import { useMemo,useState } from "react";
import { createClient } from "genlayer-js";
import { studionet } from "genlayer-js/chains";
import { TransactionStatus } from "genlayer-js/types";
import { BookOpenCheck,ExternalLink,FileClock,Landmark,Link2,LoaderCircle,SearchCheck,ShieldCheck,WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";
declare global { interface Window { ethereum?: unknown } }
type Case={case_id:string;owner:string;auditor:string;procedure_id:string;status:string;tender_notice:string;award_notice:string;last_publication_date:string;criteria:Array<{criterion_id:string;text:string;type:string;weight:string;source_pointer:string}>;revision_count:number};
const PROCEDURE="f78fe5bc-095c-4053-a1de-8c63d1154e15", TENDER="616030-2024", AWARD="4-2025", CONTRACT="0x3b5eE5e170D54152f526686Ae13531B00d5F41Df", EXPLORER="https://explorer-studio.genlayer.com";

export default function Home(){
 const [account,setAccount]=useState(""),[contract,setContract]=useState(CONTRACT),[caseId,setCaseId]=useState("0"),[busy,setBusy]=useState("");
 const [record,setRecord]=useState<Case|null>(null),[revision,setRevision]=useState<Record<string,unknown>|null>(null),[journal,setJournal]=useState<Array<{label:string;hash:string}>>([]);
 const valid=/^0x[0-9a-fA-F]{40}$/.test(contract), readClient=useMemo(()=>createClient({chain:studionet}),[]);
 async function connect(){if(!window.ethereum)return toast.error("No injected wallet found.");try{const accounts=await(window.ethereum as {request:(x:{method:string})=>Promise<string[]>}).request({method:"eth_requestAccounts"});const selected=accounts[0];const client=createClient({chain:studionet,account:selected as `0x${string}`,provider:window.ethereum});await client.connect("studionet");setAccount(selected);toast.success("Wallet connected to StudioNet")}catch(e){toast.error(e instanceof Error?e.message:"Wallet connection cancelled")}}
 function saveContract(v:string){v=v.trim();setContract(v);localStorage.setItem("awardtrace.contract",v);setRecord(null);setRevision(null)}
 async function readBack(id:string){const raw=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_case",args:[id]});if(raw==="NOT_FOUND")throw new Error("Case not found");const parsed=JSON.parse(String(raw)) as Case;setRecord(parsed);if(parsed.revision_count>0){const rev=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_revision",args:[id,String(parsed.revision_count-1)]});setRevision(JSON.parse(String(rev)))}else setRevision(null)}
 async function refresh(id=caseId){if(!valid)return toast.error("Set the deployed v4 contract address first.");setBusy("read");try{await readBack(id);toast.success("Authoritative contract state loaded.")}catch(e){toast.error(e instanceof Error?e.message:"Read failed")}finally{setBusy("")}}
 async function write(label:string,method:string,args:string[]){if(!valid)return toast.error("Set the deployed v4 contract address first.");if(!account||!window.ethereum)return toast.error("Connect a funded StudioNet wallet first.");setBusy(method);try{const version=JSON.parse(String(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_contract_version",args:[]})));if(version.name!=="AwardTrace"||version.version!==4||version.schema!=="ted-eforms-two-party-trace-v1")throw new Error("This is not the TED eForms v4 deployment.");let targetId=caseId,countBefore=-1;if(method==="create_case"){countBefore=Number(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}));targetId=String(countBefore)}const client=createClient({chain:studionet,account:account as `0x${string}`,provider:window.ethereum});await client.connect("studionet");const hash=String(await client.writeContract({address:contract as `0x${string}`,functionName:method,args,value:0n})) as `0x${string}`;setJournal(x=>[{label,hash},...x]);toast.info("Signed. Waiting for finality…");await readClient.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});if(method==="create_case"){const countAfter=Number(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}));if(countAfter!==countBefore+1)throw new Error("Finalized, but case count did not advance exactly once");setCaseId(targetId)}await readBack(targetId);toast.success(`${label}: finalized and authoritative state confirmed.`)}catch(e){toast.error(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
 const disabled=!valid||!account||Boolean(busy);
 return <main className="min-h-screen bg-[#f5f8fc] text-[#071b3d]"><Toaster position="top-right" richColors/>
  <header className="sticky top-0 z-40 border-b border-[#c9d8ec] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-3 lg:px-9"><div className="flex items-center gap-3"><Image src="/awardtrace-logo.png" alt="AwardTrace" width={48} height={48} className="rounded-xl" priority/><div><p className="text-lg font-black">AwardTrace</p><p className="text-xs text-[#557092]">Public procurement decision trace</p></div></div><div className="hidden rounded-full border border-[#c7d8ed] bg-[#f8fbff] px-4 py-2 font-mono text-xs md:block">StudioNet · {valid?`${contract.slice(0,8)}…${contract.slice(-6)}`:"deployment pending"}</div><button onClick={connect} className="action primary"><WalletCards size={18}/>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></div></header>
  <section className="mx-auto max-w-[1500px] px-5 py-8 lg:px-9"><div className="mb-7 grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
   <div className="blueprint relative overflow-hidden rounded-[30px] p-7 text-white lg:p-10"><div className="relative z-10 max-w-2xl"><div className="eyebrow text-[#9ed2ff]">OFFICIAL SOURCE → BOUNDED CONSENSUS → PUBLIC TRACE</div><h1 className="mt-4 text-4xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl">Trace the reason,<br/><span className="text-[#62b2ff]">criterion by criterion.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-[#d8e9ff]">Anchor published tender criteria before an award, then map official award reasoning without treating bidder-authored evidence as ground truth.</p></div><Landmark className="absolute -bottom-12 right-3 h-64 w-64 text-white/5" strokeWidth={1}/></div>
   <div className="panel p-6 lg:p-8"><div className="flex items-center justify-between"><div><div className="eyebrow">ACTIVE SOURCE ADAPTER</div><h2 className="mt-2 text-xl font-black">TED eForms</h2></div><ShieldCheck className="text-[#087ac1]"/></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt>Authority</dt><dd>EU Publications Office</dd></div><div><dt>Transport</dt><dd>Search API v3</dd></div><div><dt>Bound identity</dt><dd>Procedure + publication no.</dd></div><div><dt>Integrity</dt><dd>Consensus + raw SHA-256</dd></div></dl><a className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#075ea7]" href={`https://ted.europa.eu/en/notice/-/detail/${TENDER}`} target="_blank">Inspect official tender <ExternalLink size={15}/></a></div>
  </div>
  <div className="mb-6 panel grid gap-4 p-5 md:grid-cols-[1fr_auto]"><label className="field"><span>Deployed contract address</span><input value={contract} onChange={e=>saveContract(e.target.value)} placeholder="Deploy with the primary wallet, then paste 0x…"/></label><div className="flex items-end"><button className="action secondary w-full md:w-auto" onClick={()=>refresh()} disabled={!valid||Boolean(busy)}>{busy==="read"?<LoaderCircle className="animate-spin"/>:<SearchCheck/>}Read contract</button></div></div>
  <Tabs defaultValue="operate" className="gap-5"><TabsList aria-label="AwardTrace sections" className="h-auto w-full justify-start gap-2 overflow-x-auto rounded-2xl border border-[#a9c4e2] bg-[#eaf3ff] p-2 shadow-[0_8px_24px_rgba(7,94,167,.12)]"><TabsTrigger value="operate" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">Operate</TabsTrigger><TabsTrigger value="trace" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">Trace matrix</TabsTrigger><TabsTrigger value="history" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">History</TabsTrigger><TabsTrigger value="evidence" className="min-w-36 border-[#bfd2e8] bg-white px-5 py-3 font-bold text-[#284d75] shadow-sm hover:border-[#78a8d5] hover:bg-[#f7fbff] data-[state=active]:border-[#075ea7] data-[state=active]:bg-[#075ea7] data-[state=active]:text-white data-[state=active]:shadow-[0_7px_16px_rgba(7,94,167,.28)]">Evidence</TabsTrigger></TabsList>
   <TabsContent value="operate"><div className="grid gap-5 xl:grid-cols-3"><section className="panel p-6"><Head icon={<BookOpenCheck/>} over="01 · EVIDENCE CURATOR" title="Anchor official tender"/><div className="mt-6 space-y-4"><Input id="procedure" label="TED procedure ID" value={PROCEDURE}/><Input id="tenderNotice" label="Tender publication number" value={TENDER}/><Input id="auditor" label="Independent auditor wallet" value=""/></div><button disabled={disabled} className="action primary mt-5" onClick={()=>write("Create case","create_case",[val("procedure"),val("tenderNotice"),val("auditor")])}>Register TED procedure</button><button disabled={disabled} className="action secondary mt-3" onClick={()=>write("Anchor tender","anchor_tender",[caseId])}>Extract published criteria</button></section>
   <section className="panel p-6"><Head icon={<FileClock/>} over="02 · CURATOR → AUDITOR" title="Bind and assess award"/><label className="field mt-6 max-w-40"><span>Case ID</span><input value={caseId} onChange={e=>setCaseId(e.target.value)}/></label><div className="mt-4 space-y-4"><Input id="awardNotice" label="Award publication number" value={AWARD}/></div><div className="mt-5 grid gap-3"><button disabled={disabled} className="action secondary" onClick={()=>write("Bind award","bind_award",[caseId,val("awardNotice")])}>Bind later award notice</button><button disabled={disabled} className="action primary" onClick={()=>write("Assess award","assess_award",[caseId])}>Independent assessment</button></div><p className="mt-5 text-sm leading-6 text-[#38577e]">Curator binds the notice. Only the assigned auditor wallet can assess it.</p></section>
   <section className="panel p-6"><Head icon={<Link2/>} over="03 · OPTIONAL CORRECTION" title="Append official correction"/><div className="mt-6 space-y-4"><Input id="correctionNotice" label="Correction publication number" value=""/></div><div className="mt-5 grid gap-3"><button disabled={disabled} className="action secondary" onClick={()=>write("Append correction","append_correction",[caseId,val("correctionNotice")])}>Bind correction notice</button><button disabled={disabled} className="action secondary" onClick={()=>write("Assess correction","assess_correction",[caseId])}>Auditor assesses correction</button><button disabled={disabled} className="action primary" onClick={()=>write("Freeze trace","freeze_trace",[caseId])}>Freeze trace</button></div><div className="mt-6 rounded-2xl bg-[#eef5ff] p-4 text-sm leading-6 text-[#38577e]">Notice phase, procedure identity, chronology and reuse are verified on-chain from TED.</div></section></div></TabsContent>
   <TabsContent value="trace"><section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#d4e0ef] p-6"><div><div className="eyebrow">CURRENT CANONICAL REVISION</div><h2 className="mt-1 text-2xl font-black">{String(revision?.summary||"No assessed trace")}</h2></div><span className="status">{record?.status||"NOT LOADED"}</span></div><div className="overflow-x-auto"><table><thead><tr><th>Criterion</th><th>Published criterion + source</th><th>Relation</th><th>Cited award evidence</th></tr></thead><tbody>{record?.criteria.length?record.criteria.map((c,i)=>{const row=(revision?.trace as Array<Record<string,unknown>>|undefined)?.[i];return <tr key={c.criterion_id}><td className="font-mono font-bold">{c.criterion_id}</td><td>{c.text}<code className="mt-2 block text-xs text-[#557092]">{c.source_pointer}</code></td><td><span className="relation">{String(row?.relation||"PENDING")}</span></td><td><code className="text-xs">{String(row?.award_reference||"—")}</code><p className="mt-2 max-w-md text-sm">{String(row?.award_excerpt||"No cited passage")}</p></td></tr>}):<tr><td colSpan={4} className="py-14 text-center text-[#69809e]">Load a case to inspect its criterion-level trace.</td></tr>}</tbody></table></div></section></TabsContent>
   <TabsContent value="history"><div className="grid gap-5 lg:grid-cols-[1fr_.72fr]"><section className="panel p-6"><Head icon={<Link2/>} over="APPEND-ONLY LINEAGE" title="Notice chain"/><div className="mt-7 timeline"><div><b>Tender notice</b><span>{record?.tender_notice||"Awaiting case"}</span></div><div><b>Award/correction notice</b><span>{record?.award_notice||"Not bound"}</span></div><div><b>Stored revisions</b><span>{record?.revision_count??0}</span></div></div></section><section className="panel p-6"><div className="eyebrow">TRANSACTION JOURNAL</div><div className="mt-4 space-y-3">{journal.length?journal.map(x=><a key={x.hash} className="journal" href={`${EXPLORER}/tx/${x.hash}`} target="_blank"><span>{x.label}</span><code>{x.hash.slice(0,10)}…{x.hash.slice(-8)}</code></a>):<p className="text-sm text-[#69809e]">Signed writes will appear here with Explorer links.</p>}</div></section></div></TabsContent>
   <TabsContent value="evidence"><section className="panel p-6 lg:p-8"><div className="eyebrow">LIVE SOURCE MANIFEST</div><h2 className="mt-2 text-2xl font-black">Real published evidence, not fixtures</h2><div className="mt-7 grid gap-4 md:grid-cols-3"><Evidence title="Tender" detail="TED eForms · competition notice" value={TENDER}/><Evidence title="Award" detail="TED eForms · result notice" value={AWARD}/><Evidence title="Identity join" detail="Shared official procedure ID" value="f78fe5bc…4e15"/></div><div className="mt-7 grid gap-3 md:grid-cols-3"><ProofLink label="Criteria anchored" hash="0x16568f8658dcc4f523b1122be25ffc6ca2b7eef49b5a4a4af7b5319cebd35f27"/><ProofLink label="Independent assessment · FULLY_TRACED" hash="0x57df5660d00bd66888c6aa8070ce3f825748a34dafff60100ec299c00524a658"/><ProofLink label="Trace frozen" hash="0x98b53c93620878c0aa1502e80f8545a74929fd625c6e8b8549c32881b38ad42f"/></div><p className="mt-6 max-w-3xl text-sm leading-7 text-[#4c6688]">The contract posts deterministic publication-number queries to the anonymous TED Search API v3. It requires one exact result, matching procedure identity, correct notice phase, chronological publication, and validator consensus. Case 0 is frozen after a finalized FULLY_TRACED assessment. AwardTrace reports evidence coverage, not legality or fairness.</p></section></TabsContent>
  </Tabs></section></main>
}
const val=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;
function Head({icon,over,title}:{icon:React.ReactNode;over:string;title:string}){return <div className="section-head"><span>{icon}</span><div><div className="eyebrow">{over}</div><h2>{title}</h2></div></div>}
function Input({id,label,value}:{id:string;label:string;value:string}){return <label className="field"><span>{label}</span><input id={id} defaultValue={value}/></label>}
function Evidence({title,detail,value}:{title:string;detail:string;value:string}){return <div className="rounded-2xl border border-[#cbd9eb] bg-[#f8fbff] p-5"><p className="font-black">{title}</p><p className="mt-1 text-sm text-[#68809e]">{detail}</p><code className="mt-5 block text-xs text-[#075ea7]">{value}</code></div>}
function ProofLink({label,hash}:{label:string;hash:string}){return <a className="journal" href={`${EXPLORER}/tx/${hash}`} target="_blank"><span>{label}</span><ExternalLink size={15}/></a>}
